## Droput
***
***
Time: 2020-09-16<br>
Author: dsy
***

In [1]:
import numpy as np
import torch
seed = 0
torch.manual_seed(seed)
torch.random.manual_seed(seed)
np.random.seed(seed)

In [2]:
# dropout函数的实现
def dropout(x, level):
    if level < 0. or level >= 1: #level是概率值，必须在0~1之间
        raise ValueError('Dropout level must be in interval [0, 1].')
    retain_prob = 1. - level

    # 我们通过binomial函数，生成与x一样的维数向量。binomial函数就像抛硬币一样，我们可以把每个神经元当做抛硬币一样
    # 硬币 正面的概率为p，n表示每个神经元试验的次数
    # 因为我们每个神经元只需要抛一次就可以了所以n=1，size参数是我们有多少个硬币。
    random_tensor = np.random.binomial(n=1, p=retain_prob, size=x.shape) #即将生成一个0、1分布的向量，0表示这个神经元被屏蔽，不工作了，也就是dropout了
    
#     print("random_tensor",random_tensor)

#     x = x * random_tensor
# #     print(x)
#     x = x / retain_prob

    x = x * random_tensor  / retain_prob

    return x

In [3]:
X = np.random.randn(4,2)
X

array([[ 1.76405235,  0.40015721],
       [ 0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788],
       [ 0.95008842, -0.15135721]])

In [4]:
Y = torch.from_numpy(X).float()
Y

tensor([[ 1.7641,  0.4002],
        [ 0.9787,  2.2409],
        [ 1.8676, -0.9773],
        [ 0.9501, -0.1514]])

In [5]:
torch.nn.functional.dropout(Y,0.5,training =True)

tensor([[ 3.5281,  0.0000],
        [ 0.0000,  4.4818],
        [ 3.7351, -0.0000],
        [ 0.0000, -0.3027]])

In [6]:
dropout(X,0.5)

array([[ 3.52810469,  0.        ],
       [ 1.95747597,  4.4817864 ],
       [ 3.73511598, -1.95455576],
       [ 0.        , -0.        ]])

**去掉为0的相同位置，其它位置的数是相同的。**