## `RNN`
***
***
Time: 2020-09-13<br>
Author: dsy
***

$
\begin{aligned}
z_t & = Uh_{t-1} + Wx_t+b \\
h_t & = f(z_t) \\
y_t & = Vh_t \\
x_t \text{是网络的输入}，h_t \text{隐藏层状态}，z_t \text{隐藏层的净输入}，& f(\cdot) \text{
是非线性激活函数，通常为Logistic函数或者Tanh函数}，U \text{状态-状态权重矩阵},W \text{状态-输入权重矩阵},b\text{为偏置}
\end{aligned}
$

In [1]:
import torch
import torch.nn as nn

In [2]:
class RNNFromDsy(nn.Module):
    def __init__(self,hidden_size=10):
        super(RNNFromDsy,self).__init__()
        self.hidden_size = hidden_size
        
    def forward(self,x):
        # batch 最好是1
        self.batch,self.input_size = x.shape
        ht = torch.zeros((self.batch,self.input_size))
        U = torch.empty((self.batch,self.batch),requires_grad=True)
        W = torch.empty((self.batch,self.batch),requires_grad=True)
        b = torch.empty((self.batch,self.input_size),requires_grad=True)
        V = torch.empty((self.batch,self.batch),requires_grad=True)
        nn.init.uniform_(U)
        nn.init.uniform_(W)
        nn.init.uniform_(b)
        nn.init.uniform_(V)
        for i in range(self.hidden_size):
            ht = torch.tanh( U.matmul(ht) + W.matmul( x) + b)
        return V .matmul(ht)


In [3]:
X = torch.randn((1,1,4))

In [4]:
X[0]

tensor([[ 0.6201, -1.0239,  0.3520,  0.0545]])

In [5]:
rnnd = RNNFromDsy()
rnnd(X[0])

tensor([[ 0.3146, -0.2658,  0.3719,  0.0487]], grad_fn=<MmBackward>)

In [6]:
rnn = nn.RNN(input_size =4 , hidden_size =10,batch_first=True,bidirectional=False)
y,h = rnn(X)
y

tensor([[[-0.3538,  0.5373,  0.0080,  0.3380, -0.0278,  0.0677, -0.0126,
          -0.5869,  0.1034,  0.0157]]], grad_fn=<TransposeBackward1>)